### ISSUE TITLE
Problem with databinding

### ISSUE THREAD

**Issue by ShahadatShaki** [TheCodeYard/EllipsizedTextView#2]
`android.view.InflateException: Binary XML file line #114: Binary XML file line #114: Error inflating class com.thecodeyard.ellipsizedtextview.EllipsizedTextView
    Caused by: android.view.InflateException: Binary XML file line #114: Error inflating class com.thecodeyard.ellipsizedtextview.EllipsizedTextView
    Caused by: java.lang.reflect.InvocationTargetException`

**Comment by Spettacolo83** [comment]
I have the same issue too!
How can I fix it?

**Comment by gsavvid** [comment]
@Spettacolo83 @ShahadatShaki could you give me more information about the problem (API version, device, etc)? And perhaps paste the entire crash log? I've updated the demo app with an example that uses databinding and it seems to be working fine. Could you please give that one a try and see if there's anything different between this and your implementation?

At least, when it comes to updating `android:text` via databinding it seems to be working fine. If you're trying to update `app:ellipsis` via databinding, then it's true that you get an exception but it'll be a `NullPointerException` and not an `InvocationTargetException`. If for any reason you'd like to update `app:ellipsis` with databinding, I could add support for this but it seems to be a different issue than the original one posted here.

I appreciate the feedback.
